version: "3.8"
services:
#  jaeger-collector:
#    image: jaegertracing/jaeger-collector
#    environment:
#      - "SPAN_STORAGE_TYPE=memory"
#    ports:
#      - "14267:14267"  # thrift
#      - "14268:14268"  # HTTP api
#    networks:
#      - chordio
  jaeger:
    image: jaegertracing/all-in-one:1.17
#    networks:
#      - chordio
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  n1:
    image: ubuntu:20.04
    volumes:
      - "./dist/chordio_linux_amd64/chordio:/usr/local/bin/chordio"
    command:
      - /usr/local/bin/chordio
      - server
      - -b
      - ":1234"
      - -m
      - "5"
      - -l
      - debug
    networks:
      - chordio
  n2:
    image: ubuntu:20.04
    volumes:
      - "./dist/chordio_linux_amd64/chordio:/usr/local/bin/chordio"
    command:
      - /usr/local/bin/chordio
      - server
      - -b
      - ":2345"
      - -m
      - "5"
      - -l
      - debug
    networks:
      - chordio
  control:
    image: ubuntu:20.04
    volumes:
      - "./dist/chordio_linux_amd64/chordio:/usr/local/bin/chordio"
    command:
      - bash
    networks:
      - chordio
networks:
  chordio:
