// Code generated by mockery v1.0.0. DO NOT EDIT.

package node

import chord "github.com/kevinjqiu/chordio/chord"
import context "context"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/kevinjqiu/chordio/pb"

// MockNode is an autogenerated mock type for the Node type
type MockNode struct {
	mock.Mock
}

// AsProtobufNode provides a mock function with given fields:
func (_m *MockNode) AsProtobufNode() *pb.Node {
	ret := _m.Called()

	var r0 *pb.Node
	if rf, ok := ret.Get(0).(func() *pb.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Node)
		}
	}

	return r0
}

// ClosestPrecedingFinger provides a mock function with given fields: _a0, _a1
func (_m *MockNode) ClosestPrecedingFinger(_a0 context.Context, _a1 chord.ID) (Node, error) {
	ret := _m.Called(_a0, _a1)

	var r0 Node
	if rf, ok := ret.Get(0).(func(context.Context, chord.ID) Node); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, chord.ID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPredecessor provides a mock function with given fields: _a0, _a1
func (_m *MockNode) FindPredecessor(_a0 context.Context, _a1 chord.ID) (Node, error) {
	ret := _m.Called(_a0, _a1)

	var r0 Node
	if rf, ok := ret.Get(0).(func(context.Context, chord.ID) Node); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, chord.ID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSuccessor provides a mock function with given fields: _a0, _a1
func (_m *MockNode) FindSuccessor(_a0 context.Context, _a1 chord.ID) (Node, error) {
	ret := _m.Called(_a0, _a1)

	var r0 Node
	if rf, ok := ret.Get(0).(func(context.Context, chord.ID) Node); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, chord.ID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBind provides a mock function with given fields:
func (_m *MockNode) GetBind() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *MockNode) GetID() chord.ID {
	ret := _m.Called()

	var r0 chord.ID
	if rf, ok := ret.Get(0).(func() chord.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(chord.ID)
	}

	return r0
}

// GetPredNode provides a mock function with given fields:
func (_m *MockNode) GetPredNode() (*NodeRef, error) {
	ret := _m.Called()

	var r0 *NodeRef
	if rf, ok := ret.Get(0).(func() *NodeRef); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodeRef)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSuccNode provides a mock function with given fields:
func (_m *MockNode) GetSuccNode() (*NodeRef, error) {
	ret := _m.Called()

	var r0 *NodeRef
	if rf, ok := ret.Get(0).(func() *NodeRef); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodeRef)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// String provides a mock function with given fields:
func (_m *MockNode) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UpdateFingerTableEntry provides a mock function with given fields: ctx, s, i
func (_m *MockNode) UpdateFingerTableEntry(ctx context.Context, s Node, i int) error {
	ret := _m.Called(ctx, s, i)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Node, int) error); ok {
		r0 = rf(ctx, s, i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// setLocalNodeConstructor provides a mock function with given fields: _a0
func (_m *MockNode) setLocalNodeConstructor(_a0 localNodeConstructor) {
	_m.Called(_a0)
}

// setRemoteNodeConstructor provides a mock function with given fields: _a0
func (_m *MockNode) setRemoteNodeConstructor(_a0 remoteNodeConstructor) {
	_m.Called(_a0)
}
