// Code generated by mockery v1.0.0. DO NOT EDIT.

package node

import mock "github.com/stretchr/testify/mock"

// mockNodeConstructorOption is an autogenerated mock type for the nodeConstructorOption type
type mockNodeConstructorOption struct {
	mock.Mock
}

// apply provides a mock function with given fields: n
func (_m *mockNodeConstructorOption) apply(n canSetNodeConstructors) {
	_m.Called(n)
}
