// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chordio.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bind                 string   `protobuf:"bytes,2,opt,name=bind,proto3" json:"bind,omitempty"`
	Pred                 *Node    `protobuf:"bytes,3,opt,name=pred,proto3" json:"pred,omitempty"`
	Succ                 *Node    `protobuf:"bytes,4,opt,name=succ,proto3" json:"succ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *Node) GetPred() *Node {
	if m != nil {
		return m.Pred
	}
	return nil
}

func (m *Node) GetSucc() *Node {
	if m != nil {
		return m.Succ
	}
	return nil
}

//message FingerTable {
//    repeated FingerTableEntry entries = 1;
//}
//
//message FingerTableEntry {
//    uint32 start = 1;
//    uint32 end = 2;
//    Node successor = 3;
//}
//
type GetIDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDRequest) Reset()         { *m = GetIDRequest{} }
func (m *GetIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetIDRequest) ProtoMessage()    {}
func (*GetIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{1}
}

func (m *GetIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDRequest.Unmarshal(m, b)
}
func (m *GetIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDRequest.Marshal(b, m, deterministic)
}
func (m *GetIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDRequest.Merge(m, src)
}
func (m *GetIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetIDRequest.Size(m)
}
func (m *GetIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDRequest proto.InternalMessageInfo

type GetIDResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDResponse) Reset()         { *m = GetIDResponse{} }
func (m *GetIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetIDResponse) ProtoMessage()    {}
func (*GetIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{2}
}

func (m *GetIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDResponse.Unmarshal(m, b)
}
func (m *GetIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDResponse.Marshal(b, m, deterministic)
}
func (m *GetIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDResponse.Merge(m, src)
}
func (m *GetIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetIDResponse.Size(m)
}
func (m *GetIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDResponse proto.InternalMessageInfo

func (m *GetIDResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//
//message FindClosestFingerRequest {
//    uint32 keyID = 1;
//}
//
//message FindClosestFingerResponse {
//    Node node = 1;
//}
//
//message GetFingerTableRequest {
//}
//
//message GetFingerTableResponse {
//    FingerTable fingertable = 1;
//}
//
type JoinRingRequest struct {
	Introducer           *Node    `protobuf:"bytes,1,opt,name=introducer,proto3" json:"introducer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRingRequest) Reset()         { *m = JoinRingRequest{} }
func (m *JoinRingRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRingRequest) ProtoMessage()    {}
func (*JoinRingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{3}
}

func (m *JoinRingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRingRequest.Unmarshal(m, b)
}
func (m *JoinRingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRingRequest.Marshal(b, m, deterministic)
}
func (m *JoinRingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRingRequest.Merge(m, src)
}
func (m *JoinRingRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRingRequest.Size(m)
}
func (m *JoinRingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRingRequest proto.InternalMessageInfo

func (m *JoinRingRequest) GetIntroducer() *Node {
	if m != nil {
		return m.Introducer
	}
	return nil
}

type JoinRingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRingResponse) Reset()         { *m = JoinRingResponse{} }
func (m *JoinRingResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRingResponse) ProtoMessage()    {}
func (*JoinRingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{4}
}

func (m *JoinRingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRingResponse.Unmarshal(m, b)
}
func (m *JoinRingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRingResponse.Marshal(b, m, deterministic)
}
func (m *JoinRingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRingResponse.Merge(m, src)
}
func (m *JoinRingResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRingResponse.Size(m)
}
func (m *JoinRingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRingResponse proto.InternalMessageInfo

type FindSuccessorRequest struct {
	KeyID                uint64   `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccessorRequest) Reset()         { *m = FindSuccessorRequest{} }
func (m *FindSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*FindSuccessorRequest) ProtoMessage()    {}
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{5}
}

func (m *FindSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccessorRequest.Unmarshal(m, b)
}
func (m *FindSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *FindSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessorRequest.Merge(m, src)
}
func (m *FindSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_FindSuccessorRequest.Size(m)
}
func (m *FindSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessorRequest proto.InternalMessageInfo

func (m *FindSuccessorRequest) GetKeyID() uint64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

type FindSuccessorResponse struct {
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccessorResponse) Reset()         { *m = FindSuccessorResponse{} }
func (m *FindSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*FindSuccessorResponse) ProtoMessage()    {}
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{6}
}

func (m *FindSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccessorResponse.Unmarshal(m, b)
}
func (m *FindSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *FindSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessorResponse.Merge(m, src)
}
func (m *FindSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_FindSuccessorResponse.Size(m)
}
func (m *FindSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessorResponse proto.InternalMessageInfo

func (m *FindSuccessorResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*GetIDRequest)(nil), "GetIDRequest")
	proto.RegisterType((*GetIDResponse)(nil), "GetIDResponse")
	proto.RegisterType((*JoinRingRequest)(nil), "JoinRingRequest")
	proto.RegisterType((*JoinRingResponse)(nil), "JoinRingResponse")
	proto.RegisterType((*FindSuccessorRequest)(nil), "FindSuccessorRequest")
	proto.RegisterType((*FindSuccessorResponse)(nil), "FindSuccessorResponse")
}

func init() {
	proto.RegisterFile("chordio.proto", fileDescriptor_d572f8aeec35237e)
}

var fileDescriptor_d572f8aeec35237e = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xdb, 0xfc, 0x9d, 0xbf, 0xe0, 0x20, 0xa1, 0x9c, 0x5a, 0x14, 0xb2, 0x80, 0x2c, 0x21,
	0x75, 0x40, 0x96, 0x08, 0x0b, 0x23, 0x82, 0x0a, 0x54, 0x06, 0x86, 0xb0, 0x31, 0xa1, 0xc4, 0x16,
	0x58, 0x48, 0x76, 0xb0, 0x93, 0x81, 0x2f, 0xc4, 0xe7, 0xc4, 0x71, 0x53, 0xda, 0xb4, 0xdd, 0xec,
	0x77, 0xbe, 0x7b, 0xef, 0x77, 0x86, 0xa8, 0xfc, 0xd0, 0x86, 0x4b, 0xcd, 0x2a, 0xa3, 0x6b, 0x4d,
	0xdf, 0x80, 0x3c, 0x6b, 0x2e, 0x30, 0x86, 0x40, 0xf2, 0x64, 0x78, 0x3e, 0x9c, 0x92, 0xdc, 0x9d,
	0x10, 0x81, 0x14, 0x52, 0xf1, 0x24, 0x70, 0xca, 0x7e, 0xee, 0xcf, 0x78, 0x0a, 0xa4, 0x32, 0x82,
	0x27, 0xff, 0x9c, 0x76, 0x90, 0x85, 0xac, 0x6d, 0xcc, 0xbd, 0xd4, 0x96, 0x6c, 0x53, 0x96, 0x09,
	0xe9, 0x95, 0x5a, 0x89, 0xc6, 0x70, 0xf8, 0x28, 0xea, 0xf9, 0x2c, 0x17, 0x5f, 0x8d, 0xb0, 0x35,
	0x3d, 0x83, 0xa8, 0xbb, 0xdb, 0x4a, 0x2b, 0xbb, 0x65, 0x4d, 0x6f, 0xe0, 0xe8, 0x49, 0x4b, 0x95,
	0x4b, 0xf5, 0xde, 0xf5, 0xe0, 0x05, 0x80, 0x54, 0xb5, 0xd1, 0xbc, 0x29, 0x85, 0xf1, 0x4f, 0xff,
	0x4c, 0xd6, 0x0a, 0x14, 0x61, 0xb4, 0xea, 0x5c, 0x4c, 0xa7, 0x97, 0x30, 0x7e, 0x70, 0xe1, 0x5f,
	0x5c, 0x14, 0x61, 0xad, 0x36, 0xcb, 0x91, 0x63, 0x08, 0x3f, 0xc5, 0xf7, 0x7c, 0xd6, 0x19, 0x2f,
	0x2e, 0x34, 0x83, 0xc9, 0xc6, 0xeb, 0x2e, 0xa4, 0x03, 0x54, 0xce, 0xce, 0xef, 0x63, 0x05, 0xd8,
	0x4a, 0xd9, 0xcf, 0x10, 0xc2, 0xfb, 0x76, 0xa9, 0x38, 0x85, 0xd0, 0xa3, 0x61, 0xc4, 0xd6, 0x91,
	0xd3, 0x98, 0xf5, 0x88, 0xe9, 0x00, 0xaf, 0x60, 0x6f, 0x99, 0x14, 0x47, 0x6c, 0x03, 0x37, 0x3d,
	0x66, 0x5b, 0x18, 0x03, 0xbc, 0x85, 0xa8, 0x17, 0x0d, 0x27, 0x6c, 0x17, 0x58, 0x7a, 0xc2, 0x76,
	0x12, 0xd0, 0xc1, 0x1d, 0x79, 0x0d, 0xaa, 0xa2, 0xf8, 0xef, 0x3f, 0xfe, 0xfa, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x54, 0x5e, 0x68, 0x09, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChordClient is the client API for Chord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChordClient interface {
	GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error)
	//    rpc FindClosestFinger (FindClosestFingerRequest) returns (FindClosestFingerResponse) {
	//    }
	//
	//    rpc GetFingerTable (GetFingerTableRequest) returns (GetFingerTableResponse) {
	//    }
	//
	JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error)
	//
	//    rpc FindPredecessor (FindPredecessorRequest) returns (FindPredecessorResponse) {
	//    }
	//
	FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error)
}

type chordClient struct {
	cc grpc.ClientConnInterface
}

func NewChordClient(cc grpc.ClientConnInterface) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error) {
	out := new(GetIDResponse)
	err := c.cc.Invoke(ctx, "/Chord/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error) {
	out := new(JoinRingResponse)
	err := c.cc.Invoke(ctx, "/Chord/JoinRing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error) {
	out := new(FindSuccessorResponse)
	err := c.cc.Invoke(ctx, "/Chord/FindSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordServer is the server API for Chord service.
type ChordServer interface {
	GetID(context.Context, *GetIDRequest) (*GetIDResponse, error)
	//    rpc FindClosestFinger (FindClosestFingerRequest) returns (FindClosestFingerResponse) {
	//    }
	//
	//    rpc GetFingerTable (GetFingerTableRequest) returns (GetFingerTableResponse) {
	//    }
	//
	JoinRing(context.Context, *JoinRingRequest) (*JoinRingResponse, error)
	//
	//    rpc FindPredecessor (FindPredecessorRequest) returns (FindPredecessorResponse) {
	//    }
	//
	FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error)
}

// UnimplementedChordServer can be embedded to have forward compatible implementations.
type UnimplementedChordServer struct {
}

func (*UnimplementedChordServer) GetID(ctx context.Context, req *GetIDRequest) (*GetIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (*UnimplementedChordServer) JoinRing(ctx context.Context, req *JoinRingRequest) (*JoinRingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRing not implemented")
}
func (*UnimplementedChordServer) FindSuccessor(ctx context.Context, req *FindSuccessorRequest) (*FindSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetID(ctx, req.(*GetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_JoinRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).JoinRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/JoinRing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).JoinRing(ctx, req.(*JoinRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/FindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessor(ctx, req.(*FindSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _Chord_GetID_Handler,
		},
		{
			MethodName: "JoinRing",
			Handler:    _Chord_JoinRing_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Chord_FindSuccessor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chordio.proto",
}
