// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chordio.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bind                 string   `protobuf:"bytes,2,opt,name=bind,proto3" json:"bind,omitempty"`
	Pred                 *Node    `protobuf:"bytes,3,opt,name=pred,proto3" json:"pred,omitempty"`
	Succ                 *Node    `protobuf:"bytes,4,opt,name=succ,proto3" json:"succ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *Node) GetPred() *Node {
	if m != nil {
		return m.Pred
	}
	return nil
}

func (m *Node) GetSucc() *Node {
	if m != nil {
		return m.Succ
	}
	return nil
}

type ClosestPrecedingFingerRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosestPrecedingFingerRequest) Reset()         { *m = ClosestPrecedingFingerRequest{} }
func (m *ClosestPrecedingFingerRequest) String() string { return proto.CompactTextString(m) }
func (*ClosestPrecedingFingerRequest) ProtoMessage()    {}
func (*ClosestPrecedingFingerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{1}
}

func (m *ClosestPrecedingFingerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosestPrecedingFingerRequest.Unmarshal(m, b)
}
func (m *ClosestPrecedingFingerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosestPrecedingFingerRequest.Marshal(b, m, deterministic)
}
func (m *ClosestPrecedingFingerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosestPrecedingFingerRequest.Merge(m, src)
}
func (m *ClosestPrecedingFingerRequest) XXX_Size() int {
	return xxx_messageInfo_ClosestPrecedingFingerRequest.Size(m)
}
func (m *ClosestPrecedingFingerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosestPrecedingFingerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClosestPrecedingFingerRequest proto.InternalMessageInfo

func (m *ClosestPrecedingFingerRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ClosestPrecedingFingerResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosestPrecedingFingerResponse) Reset()         { *m = ClosestPrecedingFingerResponse{} }
func (m *ClosestPrecedingFingerResponse) String() string { return proto.CompactTextString(m) }
func (*ClosestPrecedingFingerResponse) ProtoMessage()    {}
func (*ClosestPrecedingFingerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{2}
}

func (m *ClosestPrecedingFingerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosestPrecedingFingerResponse.Unmarshal(m, b)
}
func (m *ClosestPrecedingFingerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosestPrecedingFingerResponse.Marshal(b, m, deterministic)
}
func (m *ClosestPrecedingFingerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosestPrecedingFingerResponse.Merge(m, src)
}
func (m *ClosestPrecedingFingerResponse) XXX_Size() int {
	return xxx_messageInfo_ClosestPrecedingFingerResponse.Size(m)
}
func (m *ClosestPrecedingFingerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosestPrecedingFingerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClosestPrecedingFingerResponse proto.InternalMessageInfo

func (m *ClosestPrecedingFingerResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

//
//message FindClosestFingerRequest {
//    uint32 keyID = 1;
//}
//
//message FindClosestFingerResponse {
//    Node node = 1;
//}
//
//message GetFingerTableRequest {
//}
//
//message GetFingerTableResponse {
//    FingerTable fingertable = 1;
//}
//
type JoinRingRequest struct {
	Introducer           *Node    `protobuf:"bytes,1,opt,name=introducer,proto3" json:"introducer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRingRequest) Reset()         { *m = JoinRingRequest{} }
func (m *JoinRingRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRingRequest) ProtoMessage()    {}
func (*JoinRingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{3}
}

func (m *JoinRingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRingRequest.Unmarshal(m, b)
}
func (m *JoinRingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRingRequest.Marshal(b, m, deterministic)
}
func (m *JoinRingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRingRequest.Merge(m, src)
}
func (m *JoinRingRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRingRequest.Size(m)
}
func (m *JoinRingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRingRequest proto.InternalMessageInfo

func (m *JoinRingRequest) GetIntroducer() *Node {
	if m != nil {
		return m.Introducer
	}
	return nil
}

type JoinRingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRingResponse) Reset()         { *m = JoinRingResponse{} }
func (m *JoinRingResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRingResponse) ProtoMessage()    {}
func (*JoinRingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{4}
}

func (m *JoinRingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRingResponse.Unmarshal(m, b)
}
func (m *JoinRingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRingResponse.Marshal(b, m, deterministic)
}
func (m *JoinRingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRingResponse.Merge(m, src)
}
func (m *JoinRingResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRingResponse.Size(m)
}
func (m *JoinRingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRingResponse proto.InternalMessageInfo

type FindPredecessorRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPredecessorRequest) Reset()         { *m = FindPredecessorRequest{} }
func (m *FindPredecessorRequest) String() string { return proto.CompactTextString(m) }
func (*FindPredecessorRequest) ProtoMessage()    {}
func (*FindPredecessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{5}
}

func (m *FindPredecessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPredecessorRequest.Unmarshal(m, b)
}
func (m *FindPredecessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPredecessorRequest.Marshal(b, m, deterministic)
}
func (m *FindPredecessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPredecessorRequest.Merge(m, src)
}
func (m *FindPredecessorRequest) XXX_Size() int {
	return xxx_messageInfo_FindPredecessorRequest.Size(m)
}
func (m *FindPredecessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPredecessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindPredecessorRequest proto.InternalMessageInfo

func (m *FindPredecessorRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindPredecessorResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPredecessorResponse) Reset()         { *m = FindPredecessorResponse{} }
func (m *FindPredecessorResponse) String() string { return proto.CompactTextString(m) }
func (*FindPredecessorResponse) ProtoMessage()    {}
func (*FindPredecessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{6}
}

func (m *FindPredecessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPredecessorResponse.Unmarshal(m, b)
}
func (m *FindPredecessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPredecessorResponse.Marshal(b, m, deterministic)
}
func (m *FindPredecessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPredecessorResponse.Merge(m, src)
}
func (m *FindPredecessorResponse) XXX_Size() int {
	return xxx_messageInfo_FindPredecessorResponse.Size(m)
}
func (m *FindPredecessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPredecessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindPredecessorResponse proto.InternalMessageInfo

func (m *FindPredecessorResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type FindSuccessorRequest struct {
	KeyID                uint64   `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccessorRequest) Reset()         { *m = FindSuccessorRequest{} }
func (m *FindSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*FindSuccessorRequest) ProtoMessage()    {}
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{7}
}

func (m *FindSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccessorRequest.Unmarshal(m, b)
}
func (m *FindSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *FindSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessorRequest.Merge(m, src)
}
func (m *FindSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_FindSuccessorRequest.Size(m)
}
func (m *FindSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessorRequest proto.InternalMessageInfo

func (m *FindSuccessorRequest) GetKeyID() uint64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

type FindSuccessorResponse struct {
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccessorResponse) Reset()         { *m = FindSuccessorResponse{} }
func (m *FindSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*FindSuccessorResponse) ProtoMessage()    {}
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{8}
}

func (m *FindSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccessorResponse.Unmarshal(m, b)
}
func (m *FindSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *FindSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessorResponse.Merge(m, src)
}
func (m *FindSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_FindSuccessorResponse.Size(m)
}
func (m *FindSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessorResponse proto.InternalMessageInfo

func (m *FindSuccessorResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetNodeInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeInfoRequest) Reset()         { *m = GetNodeInfoRequest{} }
func (m *GetNodeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoRequest) ProtoMessage()    {}
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{9}
}

func (m *GetNodeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoRequest.Unmarshal(m, b)
}
func (m *GetNodeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoRequest.Merge(m, src)
}
func (m *GetNodeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoRequest.Size(m)
}
func (m *GetNodeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoRequest proto.InternalMessageInfo

type GetNodeInfoResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeInfoResponse) Reset()         { *m = GetNodeInfoResponse{} }
func (m *GetNodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoResponse) ProtoMessage()    {}
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d572f8aeec35237e, []int{10}
}

func (m *GetNodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoResponse.Unmarshal(m, b)
}
func (m *GetNodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoResponse.Merge(m, src)
}
func (m *GetNodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoResponse.Size(m)
}
func (m *GetNodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoResponse proto.InternalMessageInfo

func (m *GetNodeInfoResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*ClosestPrecedingFingerRequest)(nil), "ClosestPrecedingFingerRequest")
	proto.RegisterType((*ClosestPrecedingFingerResponse)(nil), "ClosestPrecedingFingerResponse")
	proto.RegisterType((*JoinRingRequest)(nil), "JoinRingRequest")
	proto.RegisterType((*JoinRingResponse)(nil), "JoinRingResponse")
	proto.RegisterType((*FindPredecessorRequest)(nil), "FindPredecessorRequest")
	proto.RegisterType((*FindPredecessorResponse)(nil), "FindPredecessorResponse")
	proto.RegisterType((*FindSuccessorRequest)(nil), "FindSuccessorRequest")
	proto.RegisterType((*FindSuccessorResponse)(nil), "FindSuccessorResponse")
	proto.RegisterType((*GetNodeInfoRequest)(nil), "GetNodeInfoRequest")
	proto.RegisterType((*GetNodeInfoResponse)(nil), "GetNodeInfoResponse")
}

func init() {
	proto.RegisterFile("chordio.proto", fileDescriptor_d572f8aeec35237e)
}

var fileDescriptor_d572f8aeec35237e = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0xbe, 0xf2, 0xf2, 0xde, 0x25, 0x08, 0x5e, 0x0a, 0xd4, 0x26, 0xa2, 0x99, 0xc4, 0x84,
	0x85, 0x19, 0x15, 0x5d, 0x18, 0xdd, 0x18, 0x31, 0x18, 0x5c, 0x18, 0x53, 0x77, 0xba, 0x31, 0x74,
	0x46, 0x6d, 0x34, 0x9d, 0xda, 0x29, 0x0b, 0x7f, 0xac, 0xff, 0xc5, 0x99, 0x02, 0x81, 0x7e, 0x00,
	0x8b, 0x26, 0xd3, 0x73, 0xe7, 0x9c, 0x73, 0x73, 0xee, 0x1d, 0xa8, 0x79, 0xef, 0x22, 0x62, 0xbe,
	0xa0, 0x61, 0x24, 0x62, 0x41, 0x5e, 0xc0, 0xbc, 0x17, 0x8c, 0xe3, 0x16, 0x18, 0x3e, 0xb3, 0xcb,
	0xfb, 0xe5, 0x9e, 0xe9, 0xaa, 0x13, 0x22, 0x98, 0x63, 0x3f, 0x60, 0xb6, 0xa1, 0x90, 0xff, 0x6e,
	0x72, 0xc6, 0x1d, 0x30, 0xc3, 0x88, 0x33, 0xfb, 0x8f, 0xc2, 0xaa, 0xfd, 0x0a, 0xd5, 0x44, 0x37,
	0x81, 0x74, 0x49, 0x4e, 0x3c, 0xcf, 0x36, 0x53, 0x25, 0x0d, 0x91, 0x23, 0xd8, 0x1d, 0x7c, 0x0a,
	0xc9, 0x65, 0xfc, 0x10, 0x71, 0x8f, 0x33, 0x3f, 0x78, 0x1b, 0xaa, 0x8f, 0x47, 0x2e, 0xff, 0x9a,
	0x28, 0x34, 0x6b, 0x4d, 0x2e, 0xa1, 0xbb, 0x8a, 0x20, 0x43, 0x11, 0x48, 0xae, 0xdd, 0x02, 0x65,
	0x90, 0x70, 0x16, 0x6e, 0x1a, 0x22, 0xe7, 0x50, 0xbf, 0x13, 0x7e, 0xe0, 0x2a, 0xc2, 0x5c, 0xff,
	0x00, 0xc0, 0x0f, 0xe2, 0x48, 0xb0, 0x89, 0xc7, 0xa3, 0x34, 0x67, 0xa9, 0x40, 0x10, 0x1a, 0x0b,
	0xe6, 0xd4, 0x88, 0xf4, 0xa0, 0xad, 0xac, 0x99, 0xea, 0x83, 0xa9, 0x4e, 0xa4, 0x14, 0x2b, 0x9b,
	0x3e, 0x83, 0x4e, 0xee, 0xe6, 0xe6, 0x6e, 0x0f, 0xc1, 0xd2, 0xac, 0x47, 0x95, 0x53, 0x4a, 0xdd,
	0x82, 0xca, 0x07, 0xff, 0x1e, 0xdd, 0xcc, 0x0c, 0xa6, 0x3f, 0xa4, 0x0f, 0xad, 0xcc, 0xed, 0x8c,
	0x83, 0x91, 0x77, 0xb0, 0x00, 0x6f, 0x79, 0xac, 0x81, 0x51, 0xf0, 0x2a, 0x66, 0xfa, 0xe4, 0x18,
	0x9a, 0x29, 0x74, 0x63, 0xa7, 0xfd, 0x1f, 0x03, 0x2a, 0x03, 0xbd, 0x39, 0x78, 0x01, 0xd5, 0x25,
	0x2e, 0x36, 0x69, 0x5e, 0xdf, 0xb1, 0x68, 0x81, 0x3c, 0x29, 0xe1, 0x09, 0xfc, 0x9b, 0x67, 0x8c,
	0x0d, 0x9a, 0x19, 0x94, 0xb3, 0x4d, 0x73, 0x03, 0x28, 0xe1, 0x10, 0xea, 0x99, 0x60, 0xb1, 0x43,
	0x8b, 0x87, 0xe2, 0xd8, 0x74, 0xc5, 0x0c, 0x94, 0xce, 0x15, 0xd4, 0x52, 0xe1, 0x61, 0x8b, 0x16,
	0x45, 0xef, 0xb4, 0x69, 0x61, 0xc6, 0x4a, 0xe1, 0x19, 0xda, 0xc5, 0x7b, 0x89, 0x5d, 0xba, 0x76,
	0xc3, 0x9d, 0x3d, 0xba, 0x7e, 0xa1, 0x49, 0xe9, 0xda, 0x7c, 0x32, 0xc2, 0xf1, 0xf8, 0x6f, 0xf2,
	0x28, 0x4f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x45, 0xb4, 0x47, 0x19, 0xa5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChordClient is the client API for Chord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChordClient interface {
	//    rpc GetID (GetIDRequest) returns (GetIDResponse) {
	//    }
	//
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	//    rpc FindClosestFinger (FindClosestFingerRequest) returns (FindClosestFingerResponse) {
	//    }
	//
	//    rpc GetFingerTable (GetFingerTableRequest) returns (GetFingerTableResponse) {
	//    }
	//
	JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error)
	FindPredecessor(ctx context.Context, in *FindPredecessorRequest, opts ...grpc.CallOption) (*FindPredecessorResponse, error)
	FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error)
	ClosestPrecedingFinger(ctx context.Context, in *ClosestPrecedingFingerRequest, opts ...grpc.CallOption) (*ClosestPrecedingFingerResponse, error)
}

type chordClient struct {
	cc grpc.ClientConnInterface
}

func NewChordClient(cc grpc.ClientConnInterface) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, "/Chord/GetNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error) {
	out := new(JoinRingResponse)
	err := c.cc.Invoke(ctx, "/Chord/JoinRing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindPredecessor(ctx context.Context, in *FindPredecessorRequest, opts ...grpc.CallOption) (*FindPredecessorResponse, error) {
	out := new(FindPredecessorResponse)
	err := c.cc.Invoke(ctx, "/Chord/FindPredecessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error) {
	out := new(FindSuccessorResponse)
	err := c.cc.Invoke(ctx, "/Chord/FindSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) ClosestPrecedingFinger(ctx context.Context, in *ClosestPrecedingFingerRequest, opts ...grpc.CallOption) (*ClosestPrecedingFingerResponse, error) {
	out := new(ClosestPrecedingFingerResponse)
	err := c.cc.Invoke(ctx, "/Chord/ClosestPrecedingFinger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordServer is the server API for Chord service.
type ChordServer interface {
	//    rpc GetID (GetIDRequest) returns (GetIDResponse) {
	//    }
	//
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	//    rpc FindClosestFinger (FindClosestFingerRequest) returns (FindClosestFingerResponse) {
	//    }
	//
	//    rpc GetFingerTable (GetFingerTableRequest) returns (GetFingerTableResponse) {
	//    }
	//
	JoinRing(context.Context, *JoinRingRequest) (*JoinRingResponse, error)
	FindPredecessor(context.Context, *FindPredecessorRequest) (*FindPredecessorResponse, error)
	FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error)
	ClosestPrecedingFinger(context.Context, *ClosestPrecedingFingerRequest) (*ClosestPrecedingFingerResponse, error)
}

// UnimplementedChordServer can be embedded to have forward compatible implementations.
type UnimplementedChordServer struct {
}

func (*UnimplementedChordServer) GetNodeInfo(ctx context.Context, req *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (*UnimplementedChordServer) JoinRing(ctx context.Context, req *JoinRingRequest) (*JoinRingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRing not implemented")
}
func (*UnimplementedChordServer) FindPredecessor(ctx context.Context, req *FindPredecessorRequest) (*FindPredecessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPredecessor not implemented")
}
func (*UnimplementedChordServer) FindSuccessor(ctx context.Context, req *FindSuccessorRequest) (*FindSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (*UnimplementedChordServer) ClosestPrecedingFinger(ctx context.Context, req *ClosestPrecedingFingerRequest) (*ClosestPrecedingFingerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosestPrecedingFinger not implemented")
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_JoinRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).JoinRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/JoinRing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).JoinRing(ctx, req.(*JoinRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPredecessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/FindPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindPredecessor(ctx, req.(*FindPredecessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/FindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessor(ctx, req.(*FindSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_ClosestPrecedingFinger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosestPrecedingFingerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ClosestPrecedingFinger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chord/ClosestPrecedingFinger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ClosestPrecedingFinger(ctx, req.(*ClosestPrecedingFingerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _Chord_GetNodeInfo_Handler,
		},
		{
			MethodName: "JoinRing",
			Handler:    _Chord_JoinRing_Handler,
		},
		{
			MethodName: "FindPredecessor",
			Handler:    _Chord_FindPredecessor_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Chord_FindSuccessor_Handler,
		},
		{
			MethodName: "ClosestPrecedingFinger",
			Handler:    _Chord_ClosestPrecedingFinger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chordio.proto",
}
